### PR TITLE
Update forms.texy

### PR DESCRIPTION
**Pull request by jannavratil**
Fixed confusing and unclear definition of PATTERN validation rule.

### CODE REVIEW

**Comment by klimesf** [comment]
I thought about this issue for a while and I think this is okay - apart from not adding this piece of information into cs doc aswell.

If someone is using regexp, the note is probably understandable. If not, (s)he is going to skip it anyway.

To sum it up: :+1:

**Comment by klimesf** [comment]
ping @jannavratil Could you add EN version?

**Comment by dg** [comment]
Co tam dát
- testuje oproti regulárnímu výrazu celou hodnotu, tj. jako by byl obalen znaky `^` a `$`
- tests against regular expression entire value, somewhat as if it is inside `^` and a `$`

**Comment by jannavratil** [comment]
Ještě to squashnu do jednoho commitu, až budu mít chvilku.

**Comment by dg** [comment]
ping @jannavratil

**Comment by jannavratil** [comment]
Done. Sorry for delay.

**Comment by dg** [comment]
Thanx

**Pull request merged**
