### PR TITLE
Localization: added warning about no default translator

### PR DESCRIPTION
**Pull request by klimesf**
ref http://forum.nette.org/cs/17100-co-vylepsit-na-dokumentaci

If you believe there are more ITranslator implementations that should be linked, please tell me.

### CODE REVIEW

**Comment by Majkl578** [comment]
https://packagist.org/search/?tags%5B%5D=translation&tags%5B%5D=nette
Not sure it's unbiased to mention just one solution...

**Comment by klimesf** [comment]
Bazo/Translation is a companion extension for Kdyby/Translation. Nella Translation seems to not be in active development. Mazagran/Translation is a clone package of Bazo. Sakren's Nette-Translator looks like the only one worthy.

**Comment by klimesf** [comment]
Anything wrong or mergeable?

**Comment by klimesf** [comment]
Thanks :+1:

**Pull request merged**
