### PR TITLE
Update php-language-enhancements.texy (typo)

### PR DESCRIPTION
**Pull request by mrtnzlml**
Just a little typo... :)

### CODE REVIEW

**Comment by dg** [comment]
http://slovnik.seznam.cz/en-cz/word/?q=latter&id=TmUR65LF6Go=

**Comment by klimesf** [comment]
@mrtnzlml Could you squash the commits, please? :)

**Comment by mrtnzlml** [comment]
@klimesf rebased

**Comment by klimesf** [comment]
Thank you! :)

**Pull request merged**
