### PR TITLE
clarification of passing arguments to render()

### PR DESCRIPTION
**Pull request by poliak9**
From the original description it wasn't obvious that the render method gets the parameters, not the Presenter method.

### CODE REVIEW

**Comment by f3l1x** [comment]
Personally, I would add only `Ty se předají až metodě `render()`.`.

**Comment by f3l1x** [comment]
Personally, I would add only `Ty se předají až metodě `render()`.`. Good job btw!

**Comment by poliak9** [comment]
Gonna create new pull request. Thanks for the improvement

**Comment by f3l1x** [comment]
@poliak9 You needn't create a new PR. You can force push to this branch.

**Comment by poliak9** [comment]
@f3l1x too late sorry, next time!

**Pull request closed without merging**
