### PR TITLE
user-defined macros - link to configuring docs

### PR DESCRIPTION
**Pull request by xpavp03**

### CODE REVIEW

**Comment by xpavp03** [comment]
@chemix I don't get this. It's still possible to register macros globally in config.neon (at least the [docs say so](https://doc.nette.org/en/2.3/configuring#toc-latte)) but you don't want to tell the users when they're reading about how to register their macros? It's like hey you can also do this, but hush, don't tell anybody. Only available to people who enjoy reading long pages of documentation.

Your tip may be correct ("...register ... only in presenters where it will be used.") but if there's a way for doing it once and for all, why wouldn't you want to tell the programmer?

**Comment by chemix** [comment]
I think yes, but it's not recomended way to do this. And I think if we write this to basics docs, lot of new adopters use this not recomendet way.

**Comment by xpavp03** [comment]
I think we should either mention it thoroughly, or not mention it at all. If the method is okay in some context but not recommended in other, let's make it clear when it is okay and when not.

Sort of mentioning it but only somewhere is not a proper solution. Doesn't express "not recommended and why" at all.

**Comment by chemix** [comment]
Ok, create please new PR on doc 2.3 and open discusion there. 

"There is another way how to registred filters, but it's not recomended if you dont understand how it works...???"

**Pull request closed without merging**
