### PR TITLE
typo fix in form class - due to 1526

### PR DESCRIPTION
**Pull request by Lukeluha**
Due to https://github.com/nette/nette/issues/1526 - it is not clearly that which namespace I have to use

### CODE REVIEW

**Comment by dg** [comment]
Leading \ is not neccessary

**Comment by Lukeluha** [comment]
In `SignPresenter`, which is mentioned in quickstart, isn't neccessary, you are right. I've corrected it.

**Comment by dg** [comment]
Thanks. The last think: in Nette is usually prefered new Class without braces, can you remove it?

**Comment by Lukeluha** [comment]
Done. Hope it's now OK :)

**Comment by dg** [comment]
Thanks!

**Comment by Lukeluha** [comment]
Maybe I have one more question. As mentioned, this pull request is typo fix for issue https://github.com/nette/nette/issues/1526. My question is: why is the ticket closed if all of us known that it is typo bug? Why it isn't opened until someone noticed it and resolved it? I've noticed this bug after reading http://www.sitepoint.com/nette-framework-first-impressions/. If it were still opened, someone could noticed it and resolved it much better and sooner without reading this article...

**Comment by dg** [comment]
Maybe it was my fault. According [to this](https://github.com/nette/tutorial-quickstart/blob/master/app/presenters/SignPresenter.php#L6) it would not be a problem.

**Comment by Majkl578** [comment]
Well, technically, it wasn't a bug, since there is a `use` clause for `Nette\Application\UI\Form` in the presenter file: https://github.com/nette/tutorial-quickstart/blob/7baebd1ba172577a3238dca292fa701c1c9e10cb/app/presenters/SignPresenter.php#L6

But I admit it might be confusing in the quickstart where only portion of code is shown...

**Comment by lukasslevercz** [comment]
Maybe In quickstart repository, but not in sandbox repository (https://github.com/nette/sandbox). And in quickstart there is hint here (http://doc.nette.org/cs/2.3/quickstart/getting-started) that you should download nette/sandbox project.

**Pull request merged**
