### PR TITLE
refactoring-model.texy english translation

### PR DESCRIPTION
**Pull request by Alcariss**
As requested by Chemix, this part has been translated to English.

### CODE REVIEW

**Comment by chemix** [comment]
thank you @kebabkova @Alcariss

**Comment by dg** [comment]
Thanks, great!

**Comment by dg** [comment]
@chemix better is to merge via squash, https://help.github.com/articles/about-pull-request-merge-squashing/

**Comment by chemix** [comment]
@dg amazing, I will use it next time.

**Pull request merged**
