### PR TITLE
Fix ContainerPanel namespace

### PR DESCRIPTION
**Pull request by romanmatyus**

### CODE REVIEW

**Comment by dg** [comment]
Why is there Nette\Bridges\DITracy\ContainerPanel, when it is added automatically?

**Comment by romanmatyus** [comment]
It's only example.
Btw, I do not have it automatically. I do not know why.

**Comment by fprochazka** [comment]
@romanmatyus you have to enable it

```
container:
    debugger: on
```

**Comment by romanmatyus** [comment]
@fprochazka Of Course, but this is not automatically :)
I only fix bad namespace, not solve why it's there.

**Comment by dg** [comment]
It is confusing, I don't understand what comment „alias for DI Container bar“ means , I propose to delete the line.

**Comment by romanmatyus** [comment]
You mean entire lines?

**Comment by dg** [comment]
Line with `ContainerPanel`.

**Comment by fprochazka** [comment]
@romanmatyus oh, my bad! I agree it would be better to remove the line entirely

**Pull request merged**
