### PR TITLE
ajax: fixed caution about nette.ajax.js

### PR DESCRIPTION
**Pull request by klimesf**
Based on [this discussion](https://github.com/nette/sandbox/issues/62#issuecomment-68597641), I've fixed caution about nette.ajax.js.

### CODE REVIEW

**Comment by dg** [comment]
:+1:

**Comment by Vrtak-CZ** [comment]
Could you squash it in to one commit?

**Comment by klimesf** [comment]
Squashed.

**Comment by Vrtak-CZ** [comment]
merged https://github.com/nette/web-content/commit/df60234bbdea1f537f3fd928476396ef0c70da89

**Pull request closed without merging**
